
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  labels:
    nerd: "someone"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: podinfo
      nerd: "someone"
  template:
    metadata:
      labels:
        app: podinfo
        nerd: "someone"
    spec:
      containers:
        - name: podinfo
          image: "stefanprodan/podinfo:latest"
          ports:
            - containerPort: 9898
